### ISSUE TITLE
écrire fiche sur le cas des panneaux d'agglomération

### ISSUE THREAD

**Issue by pegautreau** [IGNF/pano#6]
## Contexte

En calculant une base des vitesses limites autorisées à partir des panneaux, il est apparu que : 

* Il était délicat d'avoir une couverture exhaustive des entrées/sorties de villes (EB10 / EB20)
* Les limitations à 50 km/h avaient tendances à "déborder" très loin des villes (vu que les règles de cheminements sont différentes pour ces panneaux zonaux : pas d'arrêt sur les intersections,...)

Il a été jugé utile de **matérialiser les zones entourées par ces EB10 / EB20** par des polygones et d'**affecter la limitation de vitesse aux tronçons inclus dans la zone** pour avoir de meilleurs résultats.

## Actions

Rédiger [doc/pano.agglomerations.md](https://github.com/IGNF/pano/blob/main/doc/pano.agglomerations.md) pour : 

* [x] Décrire le concept de "zone_panneaux" correspondant
* [x] Décrire l'algorithme d'initialisation de ces "zone_panneaux" à partir des EB10 et EB20
* [x] Expliquer les limites de l'algorithme et la possibilité de compléter par une édition des zones (en ajoutant des points entre les panneaux)

**Comment by pegautreau** [comment]
@mborne J'ai mis le [doc/pano.agglomerations.md](https://github.com/IGNF/pano/blob/main/doc/pano.agglomerations.md) à jour dans la branche issue_6

**Comment by mborne** [comment]
@pegautreau j'ai osé quelques retouches, bon pour merger de mon côté
